### ISSUE TITLE
Material Design and StudyJams no longer work

### ISSUE THREAD

**Issue by adamyi** [chenzhuo914/google-cn-devsites-extension#11]
The md.gl domain appears to be expired.

@chenglu the SJ server is down... Since we are no longer having SJ events in CN now, do you plan to have the site running for archive/historical issues? If not, I'd say we can remove it from the chrome extension. (btw, I'm not very familiar with SJ but by seeing all the comments I'm sure that u have done a great job organizing it and helping people lol ^_^)

**Comment by chenzhuo914** [comment]
Thanks for reporting this, Adam! Fixed in d017f17e10710787a3a557557d13e2ce7048b6c3.
