### ISSUE TITLE
部分国内域名已经无法访问了

### ISSUE THREAD

**Issue by xiaoxiyao** [chenzhuo914/google-cn-devsites-extension#12]
[maps.google.cn](//maps.google.cn)
[ditu.google.cn](//ditu.google.cn)
[google.cn/maps](//google.cn/maps)
[caijing.google.cn](//caijing.google.cn)

麻烦把这些映射去掉吧

**Comment by chenzhuo914** [comment]
Fixed in https://github.com/chenzhuo914/google-cn-devsites-extension/commit/e9641614e29ddacaa8ecf05719ea23cdef5dd9b7.
