### ISSUE TITLE
migrating to manifest v3

### ISSUE THREAD

**Issue by yin1999** [chenzhuo914/google-cn-devsites-extension#14]
I almost completed the migration to `manifest v3`. The job I have done is [here](https://github.com/yin1999/google-cn-devsites-extension/tree/manifest_v3)

Because the `webRequest` API has been [blocked](https://blog.chromium.org/2019/06/web-request-and-declarative-net-request.html) in `manifest v3`. The API should be replace by `declarativeNetRequest`, and it uses ruleset to modify network requests.

## Using DynamicRules or statis rulesets
Comparing with the [DynamicRules](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateDynamicRules), the [static ruleset](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateEnabledRulesets) is easier to enable or disable(Enabling only one `ruleset_id` rather than enabling all rules for enabing modifying network requests).
```
// dynamic rules
chrome.declarativeNetRequest.updateDynamicRules({
  "addRules": [
    // rule list
  ] // or "removeRuleIds": [...] // id list of rule that need to remove
})

// static ruleset
chrome.declarativeNetRequest.updateEnabledRulesets({
    "enableRulesetIds": ["ruleset_1"] // or disableRulesetIds
})
```

rule list example:

```
[
    {
        "id": 1,
        "action": { "type": "allow" },
        "condition": {
            "urlFilter": "//careers.google.com/jobs",  // match all url started with "careers.google.com.jobs", action: just continues to all matched url
            "excludedResourceTypes": [ "other" ],
            "isUrlFilterCaseSensitive": false
        }
    }
    {
        "id": 2,
        "action": {
            "type": "redirect",
            "redirect": {
                "transform": {
                    "host": "careers.google.cn"
                }
            }
        },
        "condition": {
            "urlFilter": "//careers.google.com",  // match all url started with "careers.google.com", action: redirect to "careers.google.cn" with origin url_path
            "excludedResourceTypes": [ "other" ],
            "isUrlFilterCaseSensitive": false
        }
    }
]
```

Note that, the action type `allow` has higher priority than `redirect`, so the url `careers.google.com/jobs` will not be redirected.

## solution for generating staticRuleset

I have written the generate code in config.js, using node.js it's easier to generate `ruleset` with `url mapping` in config.js.
Also, [github Action](https://github.com/features/actions) cloud help with the generating rules. the `workflow file` is placed at [.github/workflows/buildRules.yml](https://github.com/yin1999/google-cn-devsites-extension/tree/manifest_v3), trigger it by pushing a new tag or in `Action`(as following).

![image](https://user-images.githubusercontent.com/15844309/115235653-01390580-a14d-11eb-9934-19563d4ffa7f.png)

## For test

I have packaged the extension and uploaded it to [github release](https://github.com/yin1999/google-cn-devsites-extension/releases/tag/v0.24)

**Comment by yin1999** [comment]
If you think that's ok, I will create a new PR.

Also waiting for any other suggestions

**Comment by chenzhuo914** [comment]
Hi Yin, thanks for helping to maintain this add-on. Sure please create a PR for this change. Thanks!

**Comment by yin1999** [comment]
You could create the release package by following methods.
# GitHub Action
 
Trigger [GitHub Action](https://github.com/chenzhuo914/google-cn-devsites-extension/actions/workflows/buildRules.yml) by click `Run workflow`.  
It will generate the `rules.json` automatically and then package all necessary files.  
PS: The package will be released on [GitHub Releases](https://github.com/chenzhuo914/google-cn-devsites-extension/releases).

![image](https://user-images.githubusercontent.com/15844309/117625045-2fd45a00-b1a8-11eb-9f84-12eb59f716b1.png)

# Local packaging

1. Run Command

    ```bash
    node ./config.js # node.js is required
    ```

2. Packing files

    Those files are necessary: bg.js, manifest.json, rules.json, off.png, on.png
