### ISSUE TITLE
whitelist these pages

### ISSUE THREAD

**Issue by chenglu** [chenzhuo914/google-cn-devsites-extension#3]
https://firebase.google.com/support/contact/troubleshooting
https://firebase.google.com/support/contact/bugs-features
https://firebase.google.com/support/contact/account-services

These pages were login required.

**Comment by chenzhuo914** [comment]
1. Should we whitelist all "https://firebase.google.com/support/contact/", supposing there will be more similar pages added later?

2. But there are "https://firebase.google.cn/support/contact/troubleshooting" link from "https://firebase.google.cn/support/". Meaning that even after whitelisting, the chrome extension won't change ".cn" to ".com" in this case.

3. More importantly, the "登录" links don't work on the ".cn" pages! I think there shouldn't be such pages on ".cn" site at all, and "https://firebase.google.cn/support/" should link to those pages in ".com" directly.

**Comment by chenzhuo914** [comment]
Luke, please solve #<span>3</span>, and I will solve #<span>1</span>. What do you think? :)

**Comment by chenzhuo914** [comment]
Pull request for #<span>1</span>: `https://github.com/chenzhuo914/google-cn-devsites-extension/pull/4`

**Comment by chenzhuo914** [comment]
Fixed in e614521acb5ee9984c11b42c3faf385c6c1910e8.
