### ISSUE TITLE
新版本为什么需求读取浏览记录权限？

### ISSUE THREAD

**Issue by Seamo** [chenzhuo914/google-cn-devsites-extension#6]
挺久不用了，最近回墙里打开老电脑发现黄感叹号，一看需要两个新权限，读写某些网站数据和浏览记录。
前者可以理解，但是要求浏览记录的必要性是什么呢？
求解答。

**Comment by chenzhuo914** [comment]
Hi Seamo，谢谢你的问题！

Chrome extension必须显式列出所需域名的permission（请见manifest.json[文件](https://github.com/chenzhuo914/google-cn-devsites-extension/blob/master/manifest.json)及[更新历史](https://github.com/chenzhuo914/google-cn-devsites-extension/commits/master/manifest.json)），所以当我新增了网站的映射并发布新版本后，用户就会看到黄色感叹号，要求批准新域名的权限。

关于浏览记录的权限，可能是因为当这个扩展将原URL替换成映射后的URL并打开后者（新URL）以后，需要将新URL而非原URL写入浏览记录，即需要管理浏览记录的权限。

**Comment by Seamo** [comment]
了解。感谢及时回答，这个issue目前可以close了。
之所以提问是因为刚才简单翻看代码，由于对js和chrome插件开发不太熟悉，没有找到可能和浏览记录操作相关的区块，以为是为了拿到此权限而先行写出white code以求过审，而去后续更新中进行动作，故而心生疑虑。浏览记录本身就容易戳人痛点，但您这样解释我就清楚了。
小人之心，还求理解。

**Comment by chenzhuo914** [comment]
呵呵，其实我的前端开发经验也不多，所以也要谢谢您提出问题，一起参详。在现在的网络环境中，确实需要心存疑虑，小心求证。:)

**Comment by Seamo** [comment]
国内环境简直一团糟……我一部分工作是Android开发，这一行如何流氓，从业者众所周知，但用户大多数都是蒙在鼓里，软件一安设备分分钟被翻个底朝天都是常事，不少黑手甚至被当成再正常不过的途径。这种东西见得久了，所以今天黄叹号，第一反应就是又一个那啥。现在想想真的是，唉。

**Comment by chenzhuo914** [comment]
呵呵，有条件科学上网的话，还是从Google Play上安装app吧。。。:)
